### ISSUE TITLE
Bug Found

### ISSUE THREAD

**Issue by Pbhranti0703** [Pbhranti0703/GitHubAPI#1]
There is a bug in the code.  After each calculation, system asks "Let's do next calculation? (yes/no):" in this section user compulsory needs to enter "no" if he needs to terminate the code. I tried adding "N", "n" and other characters, instead of giving error it automatically detects it as "yes" and ask me to do other calculations

**Comment by ProgVaibhav** [comment]
Hello Bhranti, Thanks for raising this Bug, I will change the code and push the new one without the bug

**Comment by Pbhranti0703** [comment]
This script doesn't exists anymore

**Comment by Pbhranti0703** [comment]
Issue can be marked as resolved as this script is no more required in the repository and hence this bug can also be ignored
